language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

branches:
  only:
    - master
    - develop

install:
  - composer self-update
  - composer install --prefer-source

before_script:
  - mkdir -p build/coverage
  - tests/travis/sphinx-setup.sh

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

notifications:
  email: false

  matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
